### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by hossam-shaheen** [bradtraversy/contact-keeper#15]
why this happened with me

**Comment by sebastiancrossa** [comment]
This issue needs more context, but I had run into this issue a couple of days ago, so I hope this explanation helps.

It just means that nodemon couldn't establish a connection to the backend. If you don't get any errors on your server.js file check your Network Access from your MongoDB cluster. You are probably getting the error because your IP address changed, to which the new one isn't whitelisted. 

Cheers, hope it helps.

**Comment by bushblade** [comment]
This issue seems to have gone stale. With a lack of information, I'm closing this as an issue.
