### ISSUE TITLE
App crashes if there is '\' in filter.

### ISSUE THREAD

**Issue by thanazer** [bradtraversy/contact-keeper#22]
The app completely crashes if we type a backslash in filter contacts input. I guess this is happening because it is trying to use backslash as an escape character.

This is the exact error:

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
(anonymous function)
src/context/contact/contactReducer.js:47
  44 | return {
  45 |   ...state,
  46 |   filtered: state.contacts.filter((contact) => {
> 47 |     const regex = new RegExp(`${action.payload}`, 'gi');
     | ^  48 |     return contact.name.match(regex) || contact.email.match(regex);
  49 |   }),
  50 | };

I've gotten around this by replacing `${action.payload}` with `${action.payload.replace('\\', '\\\\')}`.

**Comment by bushblade** [comment]
Hi @thanazer 
This is fixed in Brad's [hookfix branch](https://github.com/bradtraversy/contact-keeper/blob/53db228fa02e2f97c2ec456a07fac2983538d9be/client/src/context/contact/contactReducer.js#L62)
So I would suggest you use that code.
```js
    case FILTER_CONTACTS:
      return {
        ...state,
        filtered: state.contacts.filter(({ name, email }) => {
          const testString = `${name}${email}`.toLowerCase();
          return testString.includes(action.payload.toLowerCase());
        })
      };
```
I'll close this as an issue as we intend to keep the master branch the same as students will fine in the course.
Hope that helps.
